name: Export Donate Stats Artifact PR

on:
  pull_request:
    paths:
      - '.github/workflows/export-donate-stats-artifact-pr.yml'

permissions:
  contents: read

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload ready ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ua-free-donate-stats-1.2.5
          path: releases/ua-free-donate-stats-1.2.5.zip
          if-no-files-found: error
